#+TITLE: PL Reading Group @ IU
#+SUBTITLE: Participation
#+AUTHOR: Tianyu Chen
#+SETUPFILE: ./white_clean.theme
#+OPTIONS: ^:nil p:t num:0 author:nil

* Everyone is Welcome!

* @@html:<font color="#a90533">@@Call for Presentations@@html:</font>@@

Please send us ([[./contact.html][contact]]) a short proposal (informal; one paragraph) if you
have an idea, including but not limited to:

+ Presenting a classic work [fn:1].
+ Talking about your original work (library, language design, etc. ).
+ Tutorial (for example, how to use a proof assistant).
 

* Paper Bidding Mechanism (RFC)

We maintain [[https://docs.google.com/spreadsheets/d/1NuWy4YpqwUCiR2V9wU1nb7UOKCusfiz1jaHEHUaEg3Y/edit?usp=sharing][a queue of papers]] where every member can contribute to. New
proposals are pushed to the rear of the queue.

Paper selection is bidding-based: we maintain a sliding window with a
tentative size of 3 (arbitrarily chosen), The window starts from the head
of the queue. Members select from these 3 papers and vote for the next
one to read. We then update the queue by popping the winner.
   
* Paper Discussion

+ We expect that every participant read the paper before coming to the discussion
  session. You do not need to understand every detail, but it is recommended that
  you go through the paper and get the main idea.
+ We recommend that you bring a physical or electronic copy of the paper to the
  discussion.

* COVID & Health

+ Due to COVID-19, it *is required* to wear a mask when attending in-person meetings.
+ Food is unfortunately not provided per IU guideline "about food at events and meetings".

[fn:1] Not limited to the ones in the paper queue.
